name: Daily Cron Job

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'  # 每天 UTC 时间执行，减8小时

env:
  STEPS: 66666  # 设置步数
  STEPS_RANGE: true  # 是否使用步数范围
  STEPS_MIN: 19000  # 步数开始
  STEPS_MAX: 25000  # 步数结束

jobs:
  daily-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Set steps
        run: |
          go run main.go \
            -zepp-account=${{ secrets.ZEPP_ACCOUNT }} \
            -zepp-password=${{ secrets.ZEPP_PASSWORD }} \
            -steps=${{ env.STEPS }} \
            -steps-range=${{ env.STEPS_RANGE }} \
            -steps-min=${{ env.STEPS_MIN }} \
            -steps-max=${{ env.STEPS_MAX }}
